# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/playwrightnb',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/playwrightnb',
                'lib_path': 'playwrightnb'},
  'syms': { 'playwrightnb.core': { 'playwrightnb.core.frames_ready': ('core.html#frames_ready', 'playwrightnb/core.py'),
                                   'playwrightnb.core.get_full_content': ('core.html#get_full_content', 'playwrightnb/core.py'),
                                   'playwrightnb.core.get_page': ('core.html#get_page', 'playwrightnb/core.py'),
                                   'playwrightnb.core.page_ready': ('core.html#page_ready', 'playwrightnb/core.py'),
                                   'playwrightnb.core.read_page': ('core.html#read_page', 'playwrightnb/core.py'),
                                   'playwrightnb.core.read_page_async': ('core.html#read_page_async', 'playwrightnb/core.py'),
                                   'playwrightnb.core.wait_page': ('core.html#wait_page', 'playwrightnb/core.py')},
            'playwrightnb.patch': {}}}
